/**
 * Architect Rule Loader Script V4
 * 
 * New Features:
 * - External JSON configuration (config/loader-config.json)
 * - Smart Version Detection (Vue 2 vs Vue 3)
 */

const fs = require('fs');
const path = require('path');

// --- Configuration ---
const RULES_ROOT = path.resolve(__dirname, '../rules');
const CONFIG_PATH = path.resolve(__dirname, '../config/loader-config.json');

/**
 * Load configuration from JSON file
 */
function loadConfig() {
    if (!fs.existsSync(CONFIG_PATH)) {
        console.error(`[Architect] Config file not found: ${CONFIG_PATH}`);
        process.exit(1);
    }
    const config = JSON.parse(fs.readFileSync(CONFIG_PATH, 'utf-8'));
    return {
        LAYERS: {
            BASE: config.layers.base,
            BUSINESS: config.layers.business,
            ACTION: config.layers.action
        },
        OUTPUT_DIR_NAME: config.output.dirName,
        OUTPUT_FILE_NAME: config.output.fileName
    };
}

// --- Helpers ---

function loadRulesFromFolder(layerDir, subFolder) {
    const targetPath = path.join(layerDir, subFolder);
    if (!fs.existsSync(targetPath)) return [];

    // If simple file
    if (targetPath.endsWith('.md')) {
        return [`\n<!-- Source: ${subFolder} -->\n${fs.readFileSync(targetPath, 'utf-8')}`];
    }

    // If directory
    if (fs.statSync(targetPath).isDirectory()) {
        const files = fs.readdirSync(targetPath);
        return files
            .filter(f => f.endsWith('.md'))
            .map(f => `\n<!-- Source: ${subFolder}/${f} -->\n${fs.readFileSync(path.join(targetPath, f), 'utf-8')}`);
    }

    return [];
}

function getPackageJson(targetDir) {
    const pkgPath = path.join(targetDir, 'package.json');
    if (!fs.existsSync(pkgPath)) return {};
    return JSON.parse(fs.readFileSync(pkgPath, 'utf-8'));
}

function checkVueVersion(dependencies) {
    const vueVersion = dependencies['vue'];
    if (!vueVersion) return null;

    // Simple heuristic: check if starts with 2 or ^2
    if (vueVersion.startsWith('2') || vueVersion.startsWith('^2') || vueVersion.startsWith('~2')) {
        return 'vue2';
    }
    return 'vue3';
}

// --- Main ---

function main() {
    // Load configuration
    const { LAYERS, OUTPUT_DIR_NAME, OUTPUT_FILE_NAME } = loadConfig();

    const targetDir = process.argv[2] || process.cwd();
    console.log(`[Architect] Analyzing project at: ${targetDir}`);

    const pkg = getPackageJson(targetDir);
    const dependencies = { ...pkg.dependencies, ...pkg.devDependencies };
    const projectDeps = Object.keys(dependencies);

    // Try to load context.md as System Prompt
    const contextPath = path.join(RULES_ROOT, '..', '.codebuddy', 'context.md');
    let systemPrompt = '';
    if (fs.existsSync(contextPath)) {
        systemPrompt = fs.readFileSync(contextPath, 'utf-8');
        console.log('[Architect] Loaded context.md as System Prompt.');
    }

    let finalContent = `# Architect Rule Set
> Generated by Architect Rule Loader V4
> For: CodeBuddy / AI Coding Assistants

---

${systemPrompt}

---

## 🤖 AI 行为指令 (Behavior Instructions)

当你协助用户编写或审查代码时，请遵循以下原则：

1. **代码生成**: 所有代码必须符合 Layer 1 规则（TypeScript 严格类型、Vue 3 Script Setup）
2. **代码审查**: 发现违规时，明确指出问题并提供符合规范的替代方案
3. **决策解释**: 引用规则的 **Reasoning** 部分解释"为什么"
4. **任务适配**: 根据用户意图（重构/调试/测试）参考 Layer 3 对应的 Checklist

---
`;

    // Process Layer 1: Base
    console.log(`[Architect] Processing Base Layer...`);
    finalContent += `\n# ${LAYERS.BASE.title}\n`;
    const baseDir = path.join(RULES_ROOT, LAYERS.BASE.id);

    // 1. Load Static Base Rules (Architecture, etc)
    LAYERS.BASE.staticDeps.forEach(folder => {
        finalContent += loadRulesFromFolder(baseDir, folder).join('\n');
    });

    // 2. Load Vue Version Specific Rules
    const vueVer = checkVueVersion(dependencies);
    if (vueVer === 'vue3') {
        console.log('[Architect] Detected Vue 3. Loading Script Setup rules.');
        finalContent += loadRulesFromFolder(baseDir, 'vue3').join('\n');
    } else if (vueVer === 'vue2') {
        console.log('[Architect] Detected Vue 2. Loading Options API rules.');
        finalContent += loadRulesFromFolder(baseDir, 'vue2').join('\n');
    }

    // Process Layer 2: Business
    console.log(`[Architect] Processing Business Layer...`);
    finalContent += `\n# ${LAYERS.BUSINESS.title}\n`;
    const bizDir = path.join(RULES_ROOT, LAYERS.BUSINESS.id);

    Object.keys(LAYERS.BUSINESS.dependencies).forEach(depKey => {
        if (projectDeps.includes(depKey)) {
            console.log(`[Architect] Detected ${depKey}. Loading related rules.`);
            LAYERS.BUSINESS.dependencies[depKey].forEach(folder => {
                finalContent += loadRulesFromFolder(bizDir, folder).join('\n');
            });
        }
    });

    // Process Layer 3: Action
    console.log(`[Architect] Processing Action Layer...`);
    finalContent += `\n# ${LAYERS.ACTION.title}\n`;
    const actionDir = path.join(RULES_ROOT, LAYERS.ACTION.id);

    LAYERS.ACTION.defaults.forEach(item => {
        const fileMatches = loadRulesFromFolder(actionDir, item + '.md');
        finalContent += fileMatches.join('\n');
    });

    // Output
    const outputDir = path.join(targetDir, OUTPUT_DIR_NAME);
    if (!fs.existsSync(outputDir)) fs.mkdirSync(outputDir, { recursive: true });

    const outputPath = path.join(outputDir, OUTPUT_FILE_NAME);
    fs.writeFileSync(outputPath, finalContent, 'utf-8');
    console.log(`[Architect] Success! Rules written to ${outputPath}`);
}

main();

